# Generated by Django 6.0.2 on 2026-02-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_pessoa_sobrenome_alter_pedido_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default=1, upload_to='foto/'),
            preserve_default=False,
        ),
    ]
